Algoritmo "Orientação a Objetos"

Tipo

cadastroCliente = registro
 nome, rg: caracter
 idade: inteiro
fimregistro

Var
 clienteUm: cadastroCliente

Inicio

 Escreval("Por favor, digite seu nome: ")
 Leia(clienteUm.nome)
 
 Escreval("Me fale quantos anos você tem: ")
 Leia(clienteUm.idade)

 Escreval("Qual o número do seu rg?")
 Leia(clienteUm.rg)
 
 Escreval("Nome: ", clienteUm.nome, " Idade: ", clienteUm.idade, " e Rg: ", clienteUm.rg)
 
Fimalgoritmo